/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getNewChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'infra-new-change',
    description: 'Start a new InfraSpec change using the experimental artifact workflow. Use when the user wants to create a new feature, fix, or modification with a structured step-by-step approach.',
    instructions: `Start a new change using the experimental artifact-driven approach.

**Input**: The user's request should include a change name (kebab-case) OR requirement content describing what they want to build. The requirement content may be a plain-text requirement document that has already been preprocessed from another format.

**Steps**

1. **If no clear input provided, ask what they want to build**

   Use the **AskUserQuestion tool** (open-ended, no preset options) to ask:
   > "What change do you want to work on? Describe the requirement or paste the requirement document text."

   From their description, derive a kebab-case name (e.g., "add user authentication" → \`add-user-auth\`).

   **IMPORTANT**: Do NOT proceed without understanding the requirement content.

2. **Determine the workflow schema**

   Use the default schema (omit \`--schema\`) unless the user explicitly requests a different workflow.

   **Use a different schema only if the user mentions:**
   - A specific schema name → use \`--schema <name>\`
   - "show workflows" or "what workflows" → run \`infraspec schemas --json\` and let them choose

   **Otherwise**: Omit \`--schema\` to use the default.

3. **Create the change directory**
   \`\`\`bash
   infraspec new change "<name>"
   \`\`\`
   Add \`--schema <name>\` only if the user requested a specific workflow.
   This creates a scaffolded change in the InfraSpec workspace at \`infraspec/changes/<name>/\` with the selected schema.

4. **Create \`requirements.md\`**
   Save the requirement input to:
   \`infraspec/changes/<name>/requirements.md\`

   Convert the user's requirement input into this exact company structure:
   - \`# 需求文档\`
   - \`## 1. 需求概述\`
   - \`### 1.1 背景、目标及价值（必填）\`
   - \`### 1.2 关键指标（必填）\`
   - \`### 1.3 术语名词解释（选填）\`
   - \`## 2. 需求解析\`
   - \`### 2.1 现状分析（选填）\`
   - \`### 2.2 方案设计（选填）\`
   - \`### 2.3 功能清单（必填）\`
   - \`## 3. 影响分析\`
   - \`### 3.1 依赖评估（选填）\`
   - \`### 3.2 影响评估（选填）\`
   - \`### 3.3 安全评估（选填）\`

   Writing rules:
   - Preserve the user's original meaning.
   - Use the company-required section order exactly.
   - Fill required sections with substantive content.
   - Optional sections may be filled when supported by the input; otherwise explicitly write \`本次未明确\`.
   - If important information is missing, write \`待确认事项\` instead of inventing facts.
   - In \`2.3 功能清单\`, use stable identifiers like \`F1\`, \`F2\`, \`F3\`.

5. **STOP and wait for user direction**
   Do not create proposal.md, specs, design.md, or tasks.md in this step.

**Output**

After completing the steps, summarize:
- Change name and location
- Requirements file location
- What was saved in \`requirements.md\`
- Prompt: "Run \`/infra:review\` to generate the company-format detailed design document."

**Guardrails**
- Do NOT create any formal InfraSpec artifacts yet
- Do NOT show the first artifact template in this step
- Do NOT advance beyond saving \`requirements.md\`
- If the name is invalid (not kebab-case), ask for a valid name
- If a change with that name already exists, suggest continuing that change instead
- Pass --schema if using a non-default workflow`,
    license: 'MIT',
    compatibility: 'Requires InfraSpec CLI (`infraspec`).',
    metadata: { author: 'bianyongmei', version: '1.0' },
  };
}

export function getOpsxNewCommandTemplate(): CommandTemplate {
  return {
    name: 'INFRA: New',
    description: 'Start a new change using the experimental artifact workflow (INFRA)',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `Start a new change using the experimental artifact-driven approach.

**Input**: The argument after \`/infra:new\` is the change name (kebab-case), OR requirement content describing what the user wants to build. The requirement content may be a plain-text requirement document that has already been preprocessed from another format.

**Steps**

1. **If no input provided, ask what they want to build**

   Use the **AskUserQuestion tool** (open-ended, no preset options) to ask:
   > "What change do you want to work on? Describe the requirement or paste the requirement document text."

   From their description, derive a kebab-case name (e.g., "add user authentication" → \`add-user-auth\`).

   **IMPORTANT**: Do NOT proceed without understanding the requirement content.

2. **Determine the workflow schema**

   Use the default schema (omit \`--schema\`) unless the user explicitly requests a different workflow.

   **Use a different schema only if the user mentions:**
   - A specific schema name → use \`--schema <name>\`
   - "show workflows" or "what workflows" → run \`infraspec schemas --json\` and let them choose

   **Otherwise**: Omit \`--schema\` to use the default.

3. **Create the change directory**
   \`\`\`bash
   infraspec new change "<name>"
   \`\`\`
   Add \`--schema <name>\` only if the user requested a specific workflow.
   This creates a scaffolded change in the InfraSpec workspace at \`infraspec/changes/<name>/\` with the selected schema.

4. **Create \`requirements.md\`**
   Save the requirement input to:
   \`infraspec/changes/<name>/requirements.md\`

   Convert the user's requirement input into this exact company structure:
   - \`# 需求文档\`
   - \`## 1. 需求概述\`
   - \`### 1.1 背景、目标及价值（必填）\`
   - \`### 1.2 关键指标（必填）\`
   - \`### 1.3 术语名词解释（选填）\`
   - \`## 2. 需求解析\`
   - \`### 2.1 现状分析（选填）\`
   - \`### 2.2 方案设计（选填）\`
   - \`### 2.3 功能清单（必填）\`
   - \`## 3. 影响分析\`
   - \`### 3.1 依赖评估（选填）\`
   - \`### 3.2 影响评估（选填）\`
   - \`### 3.3 安全评估（选填）\`

   Writing rules:
   - Preserve the user's original meaning.
   - Use the company-required section order exactly.
   - Fill required sections with substantive content.
   - Optional sections may be filled when supported by the input; otherwise explicitly write \`本次未明确\`.
   - If important information is missing, write \`待确认事项\` instead of inventing facts.
   - In \`2.3 功能清单\`, use stable identifiers like \`F1\`, \`F2\`, \`F3\`.

5. **STOP and wait for user direction**
   Do not create proposal.md, specs, design.md, or tasks.md in this step.

**Output**

After completing the steps, summarize:
- Change name and location
- Requirements file location
- What was saved in \`requirements.md\`
- Prompt: "Run \`/infra:review\` to generate the company-format detailed design document."

**Guardrails**
- Do NOT create any formal InfraSpec artifacts yet
- Do NOT show the first artifact template in this step
- Do NOT advance beyond saving \`requirements.md\`
- If the name is invalid (not kebab-case), ask for a valid name
- If a change with that name already exists, suggest using \`/infra:review\` instead
- Pass --schema if using a non-default workflow`
  };
}
