/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getNewChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'infra-new-change',
    description: '使用实验性的 artifact workflow 启动一个新的 InfraSpec change。适用于用户想以结构化、分步骤的方式创建新功能、修复问题或做修改的场景。',
    instructions: `使用实验性的 artifact-driven 方式启动一个新的 change。

**Input**: 用户请求中应包含 change name（kebab-case），或者描述其想要构建内容的 requirement 内容。该 requirement 内容也可能是已经从其他格式预处理后的纯文本需求文档。

如果 \`/infra:new\` 后面的输入是一个已存在的 Markdown 文件路径，无论它是普通需求文档路径（例如 \`docs/requirements.md\`）还是头脑风暴结果路径（例如 \`infraspec/explorations/<timestamp>-<slug>/brainstorm-result.md\`），都先读取该文件，并都将文件内容作为需求描述。

**Steps**

1. **如果没有清晰输入，先询问用户要构建什么**

   使用 **AskUserQuestion tool**（开放式提问，不提供预设选项）询问：
   > "What change do you want to work on? Describe the requirement or paste the requirement document text."

   根据用户描述推导出一个 kebab-case name（例如 "add user authentication" → \`add-user-auth\`）。

   **IMPORTANT**: 在理解 requirement 内容之前，不要继续。

2. **确定 workflow schema**

   默认使用默认 schema（即省略 \`--schema\`），除非用户明确要求使用其他 workflow。

   **只有在用户提到以下情况时，才使用非默认 schema：**
   - 明确给出某个 schema name → 使用 \`--schema <name>\`
   - 提到 "show workflows" 或 "what workflows" → 运行 \`infraspec schemas --json\` 并让用户选择

   **Otherwise**: 省略 \`--schema\`，使用默认 workflow。

3. **创建 change 目录**
   \`\`\`bash
   infraspec new change "<name>"
   \`\`\`
   只有在用户要求特定 workflow 时才附加 \`--schema <name>\`。
   这会在 InfraSpec workspace 的 \`infraspec/changes/<name>/\` 下，用所选 schema 创建一个脚手架化的 change。

4. **保存原始需求描述**
   将用户提供的原始 requirement 输入保存到：
   \`infraspec/changes/<name>/requirement-description.md\`

   写作规则：
   - 尽量保留用户原始表达，不要提前改写成正式需求文档。
   - 如果用户粘贴的是长文档，也完整保存。
   - 后续所有分析都以该文件作为需求输入源。

5. **运行代码图谱分析**
   这是 workflow 的自动尝试步骤，由当前 AI agent 自动运行，不要要求用户手动执行该命令。
   在创建 \`requirements.md\` 前，必须先尝试运行：
   \`\`\`bash
   infraspec code analyze --change "<name>" --json
   \`\`\`

   该命令会读取 \`requirement-description.md\`，并生成：
   - \`infraspec/changes/<name>/code-context.md\`：代码上下文摘要
   - \`infraspec/changes/<name>/.code-context.json\`：结构化代码上下文

   如果命令执行失败、命令不可用，或返回 \`status: "unavailable"\`，不要中断 \`/infra:new\`；降级跳过代码图谱分析并继续创建 \`requirements.md\`，但在代码相关章节中明确说明代码图谱分析不可用。

   **Fallback gate**: 继续前应尽量确认 \`infraspec/changes/<name>/code-context.md\` 已存在。
   - 如果文件不存在，重新运行一次 \`infraspec code analyze --change "<name>" --json\`。
   - 如果仍然失败，手动写入一个降级版 \`code-context.md\`，说明代码图谱分析不可用及失败原因，然后继续。
   - 不允许因为代码图谱分析失败而阻止生成 \`requirements.md\`。

6. **创建 \`requirements.md\`**
   读取：
   - \`infraspec/changes/<name>/requirement-description.md\`
   - \`infraspec/changes/<name>/code-context.md\`

   基于用户的 requirement 输入和代码图谱分析结果产出 \`requirements.md\`。先识别需求目标、关键约束、现状上下文和可交付子功能，再把总需求与每个子功能的详细说明组织在同一个 \`requirements.md\` 中；子功能详情统一写入 \`3. 功能详情\`。

   使用以下精确的公司结构：
   - \`# 需求文档\`
   - \`## 1. 需求概述\`
   - \`### 1.1. 背景、目标及价值\`
   - \`### 1.2. 关键指标\`
   - \`### 1.3. 术语名词解释\`
   - \`## 2. 需求解析\`
   - \`### 2.1. 现状分析\`
   - \`### 2.2. 方案设计\`
   - \`### 2.3. 功能清单\`
   - \`## 3. 功能详情\`
   - \`### 3.1. <子功能名称>\`
   - \`#### 3.1.1. 功能概述\`
   - \`#### 3.1.2. 改造范围\`
   - \`#### 3.1.3. 验收标准\`
   - \`#### 3.1.4. 技术方案\`
   - \`#### 3.1.5. 风险与应对措施\`
   - \`### 3.2. <子功能名称>\`
   - \`#### 3.2.1. 功能概述\`
   - \`#### 3.2.2. 改造范围\`
   - \`#### 3.2.3. 验收标准\`
   - \`#### 3.2.4. 技术方案\`
   - \`#### 3.2.5. 风险与应对措施\`
   - \`### 3.N. <子功能名称>\`
   - \`#### 3.N.1. 功能概述\`
   - \`#### 3.N.2. 改造范围\`
   - \`#### 3.N.3. 验收标准\`
   - \`#### 3.N.4. 技术方案\`
   - \`#### 3.N.5. 风险与应对措施\`
   - \`## 4. 影响分析\`
   - \`### 4.1. 依赖评估\`
   - \`### 4.2. 影响评估\`
   - \`### 4.3. 安全评估\`
   - \`### 4.4. 业务性能需求描述\`
   - \`| 性能类型 | 性能需求描述 |\`
   - \`| --- | --- |\`
   - \`| 业务处理性能 | <性能需求描述> |\`
   - \`| 业务容量 | <性能需求描述> |\`
   - \`| 业务响应时间 | <性能需求描述> |\`
   - \`| 日终批处理能力 | <性能需求描述> |\`

   写作规则：
   - 保留用户原始表达的真实含义。
   - 严格使用公司要求的章节顺序。
   - 所有必填章节都要写出有实质内容的内容。
   - \`1.1. 背景、目标及价值\`、\`1.2. 关键指标\`、\`2.3. 功能清单\`、\`3. 功能详情\` 都必须写出有实质内容的内容。
   - \`2.1. 现状分析\`、\`2.2. 方案设计\`、\`3. 功能详情\`、\`4.1. 依赖评估\`、\`4.2. 影响评估\` 应优先使用 \`code-context.md\` 中的代码事实、相关模块、入口符号和影响线索。
   - 选填章节如果 requirement 或 code-context 支持则填写；否则明确写 \`本次未明确\`。
   - 如果关键信息缺失，写 \`待确认事项\`，不要编造事实。
   - 在 \`2.3. 功能清单\` 中，列出需求拆解出的所有子功能，使用稳定标识符，例如 \`F1\`、\`F2\`、\`F3\`，并与 \`3. 功能详情\` 的子功能顺序保持一致。
   - 在 \`3. 功能详情\` 中，为 \`2.3. 功能清单\` 的每个子功能创建一个 \`### 3.x. <子功能名称>\` 小节，并完整填写 \`功能概述\`、\`改造范围\`、\`验收标准\`、\`技术方案\`、\`风险与应对措施\` 五个四级标题。
   - 如果某个子功能内部还需要拆分更细的范围或对象，可在对应四级标题下继续使用五级标题，例如 \`##### 3.3.2.1. 对外展示\`，但不要跳出当前子功能小节。
   - 示例：如果“模型路由平台”被拆成“统一模型 API 网关”、“Provider Adapter 接入框架”、“模型别名与能力矩阵”，则 \`requirements.md\` 应包含 \`### 3.1. 统一模型 API 网关\`、\`### 3.2. Provider Adapter 接入框架\`、\`### 3.3. 模型别名与能力矩阵\`，每个小节下都包含 \`功能概述\`、\`改造范围\`、\`验收标准\`、\`技术方案\`、\`风险与应对措施\`。
   - \`4.4. 业务性能需求描述\` 必须作为 \`requirements.md\` 的最后一个小节，并使用固定 Markdown 表格输出；表格列为 \`性能类型\`、\`性能需求描述\`，行必须包含 \`业务处理性能\`、\`业务容量\`、\`业务响应时间\`、\`日终批处理能力\`。
   - 如果原始 requirement 明确给出性能指标，将指标写入对应表格单元格，例如 \`业务响应时间\` 可写 \`响应延迟 <= 60s\`；如果未明确，则对应单元格写 \`本次未明确\`，不要删除表格行。
   - 本步骤的唯一需求产物是 \`infraspec/changes/<name>/requirements.md\`；所有子功能内容均以内嵌章节形式写入该文件。

7. **STOP，等待用户下一步指示**
   在这一步不要创建 proposal.md、specs、design.md 或 tasks.md。

**Output**

完成以上步骤后，输出总结：
- Change name 和所在位置
- Requirement description 文件位置
- Code context 文件位置
- Requirements 文件位置
- \`requirements.md\` 中保存了什么
- Prompt: "Run \`/infra:review <name>\` to generate the lean-process detailed design specification (\`detailed-design.md\`)."

**Guardrails**
- 现在还不要创建任何正式的 InfraSpec artifacts
- 在这一步不要展示第一个 artifact template
- 不要推进到保存 \`requirements.md\` 之后的阶段
- \`requirements.md\` 是本步骤唯一需求文档；所有子功能详情均写入 \`3. 功能详情\`
- 不要让用户手动运行 \`infraspec code analyze\`；这是 workflow 内部自动步骤
- 如果代码图谱分析失败，必须保留 \`code-context.md\` 中的失败说明，并继续生成 \`requirements.md\`
- 如果 name 非法（不是 kebab-case），要求用户提供合法名称
- 如果同名 change 已存在，建议用户继续该 change，而不是新建
- 如果使用非默认 workflow，记得传入 \`--schema\``,
    compatibility: 'Requires InfraSpec CLI (`infraspec`).',
    metadata: { author: 'bianyongmei', version: '1.0' },
  };
}

export function getOpsxNewCommandTemplate(): CommandTemplate {
  return {
    name: 'INFRA: New',
    description: '使用实验性的 artifact workflow 启动一个新的 change（INFRA）',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `使用实验性的 artifact-driven 方式启动一个新的 change。

**Input**: \`/infra:new\` 后的参数可以是 change name（kebab-case），或者描述用户想构建内容的 requirement 内容。该 requirement 内容也可能是已经从其他格式预处理后的纯文本需求文档。

如果 \`/infra:new\` 后面的输入是一个文件路径，无论它是普通需求文档路径还是头脑风暴结果路径（例如 \`infraspec/explorations/<timestamp>-<slug>/brainstorm-result.md\`），都先读取该文件，并都将文件内容作为需求描述。

**Steps**

1. **如果没有提供输入，先询问用户要构建什么**

   使用 **AskUserQuestion tool**（开放式提问，不提供预设选项）询问：
   > "What change do you want to work on? Describe the requirement or paste the requirement document text."

   根据用户描述推导出一个 kebab-case name（例如 "add user authentication" → \`add-user-auth\`）。

   **IMPORTANT**: 在理解 requirement 内容之前，不要继续。

2. **确定 workflow schema**

   默认使用默认 schema（即省略 \`--schema\`），除非用户明确要求使用其他 workflow。

   **只有在用户提到以下情况时，才使用非默认 schema：**
   - 明确给出某个 schema name → 使用 \`--schema <name>\`
   - 提到 "show workflows" 或 "what workflows" → 运行 \`infraspec schemas --json\` 并让用户选择

   **Otherwise**: 省略 \`--schema\`，使用默认 workflow。

3. **创建 change 目录**
   \`\`\`bash
   infraspec new change "<name>"
   \`\`\`
   只有在用户要求特定 workflow 时才附加 \`--schema <name>\`。
   这会在 InfraSpec workspace 的 \`infraspec/changes/<name>/\` 下，用所选 schema 创建一个脚手架化的 change。

4. **保存原始需求描述**
   将用户提供的原始 requirement 输入保存到：
   \`infraspec/changes/<name>/requirement-description.md\`

   写作规则：
   - 尽量保留用户原始表达，不要提前改写成正式需求文档。
   - 如果用户粘贴的是长文档，也完整保存。
   - 后续所有分析都以该文件作为需求输入源。

5. **运行代码图谱分析**
   这是 workflow 的自动尝试步骤，由当前 AI agent 自动运行，不要要求用户手动执行该命令。
   在创建 \`requirements.md\` 前，必须先尝试运行：
   \`\`\`bash
   infraspec code analyze --change "<name>" --json
   \`\`\`

   该命令会读取 \`requirement-description.md\`，并生成：
   - \`infraspec/changes/<name>/code-context.md\`：代码上下文摘要
   - \`infraspec/changes/<name>/.code-context.json\`：结构化代码上下文

   如果命令执行失败、命令不可用，或返回 \`status: "unavailable"\`，不要中断 \`/infra:new\`；降级跳过代码图谱分析并继续创建 \`requirements.md\`，但在代码相关章节中明确说明代码图谱分析不可用。

   **Fallback gate**: 继续前应尽量确认 \`infraspec/changes/<name>/code-context.md\` 已存在。
   - 如果文件不存在，重新运行一次 \`infraspec code analyze --change "<name>" --json\`。
   - 如果仍然失败，手动写入一个降级版 \`code-context.md\`，说明代码图谱分析不可用及失败原因，然后继续。
   - 不允许因为代码图谱分析失败而阻止生成 \`requirements.md\`。

6. **创建 \`requirements.md\`**
   读取：
   - \`infraspec/changes/<name>/requirement-description.md\`
   - \`infraspec/changes/<name>/code-context.md\`

   基于用户的 requirement 输入和代码图谱分析结果产出 \`requirements.md\`。先识别需求目标、关键约束、现状上下文和可交付子功能，再把总需求与每个子功能的详细说明组织在同一个 \`requirements.md\` 中；子功能详情统一写入 \`3. 功能详情\`。

   使用以下精确的公司结构：
   - \`# 需求文档\`
   - \`## 1. 需求概述\`
   - \`### 1.1. 背景、目标及价值\`
   - \`### 1.2. 关键指标\`
   - \`### 1.3. 术语名词解释\`
   - \`## 2. 需求解析\`
   - \`### 2.1. 现状分析\`
   - \`### 2.2. 方案设计\`
   - \`### 2.3. 功能清单\`
   - \`## 3. 功能详情\`
   - \`### 3.1. <子功能名称>\`
   - \`#### 3.1.1. 功能概述\`
   - \`#### 3.1.2. 改造范围\`
   - \`#### 3.1.3. 验收标准\`
   - \`#### 3.1.4. 技术方案\`
   - \`#### 3.1.5. 风险与应对措施\`
   - \`### 3.2. <子功能名称>\`
   - \`#### 3.2.1. 功能概述\`
   - \`#### 3.2.2. 改造范围\`
   - \`#### 3.2.3. 验收标准\`
   - \`#### 3.2.4. 技术方案\`
   - \`#### 3.2.5. 风险与应对措施\`
   - \`### 3.N. <子功能名称>\`
   - \`#### 3.N.1. 功能概述\`
   - \`#### 3.N.2. 改造范围\`
   - \`#### 3.N.3. 验收标准\`
   - \`#### 3.N.4. 技术方案\`
   - \`#### 3.N.5. 风险与应对措施\`
   - \`## 4. 影响分析\`
   - \`### 4.1. 依赖评估\`
   - \`### 4.2. 影响评估\`
   - \`### 4.3. 安全评估\`
   - \`### 4.4. 业务性能需求描述\`
   - \`| 性能类型 | 性能需求描述 |\`
   - \`| --- | --- |\`
   - \`| 业务处理性能 | <性能需求描述> |\`
   - \`| 业务容量 | <性能需求描述> |\`
   - \`| 业务响应时间 | <性能需求描述> |\`
   - \`| 日终批处理能力 | <性能需求描述> |\`

   写作规则：
   - 保留用户原始表达的真实含义。
   - 严格使用公司要求的章节顺序。
   - 所有必填章节都要写出有实质内容的内容。
   - \`1.1. 背景、目标及价值\`、\`1.2. 关键指标\`、\`2.3. 功能清单\`、\`3. 功能详情\` 都必须写出有实质内容的内容。
   - \`2.1. 现状分析\`、\`2.2. 方案设计\`、\`3. 功能详情\`、\`4.1. 依赖评估\`、\`4.2. 影响评估\` 应优先使用 \`code-context.md\` 中的代码事实、相关模块、入口符号和影响线索。
   - 选填章节如果 requirement 或 code-context 支持则填写；否则明确写 \`本次未明确\`。
   - 如果关键信息缺失，写 \`待确认事项\`，不要编造事实。
   - 在 \`2.3. 功能清单\` 中，列出需求拆解出的所有子功能，使用稳定标识符，例如 \`F1\`、\`F2\`、\`F3\`，并与 \`3. 功能详情\` 的子功能顺序保持一致。
   - 在 \`3. 功能详情\` 中，为 \`2.3. 功能清单\` 的每个子功能创建一个 \`### 3.x. <子功能名称>\` 小节，并完整填写 \`功能概述\`、\`改造范围\`、\`验收标准\`、\`技术方案\`、\`风险与应对措施\` 五个四级标题。
   - 如果某个子功能内部还需要拆分更细的范围或对象，可在对应四级标题下继续使用五级标题，例如 \`##### 3.3.2.1. 对外展示\`，但不要跳出当前子功能小节。
   - 示例：如果“模型路由平台”被拆成“统一模型 API 网关”、“Provider Adapter 接入框架”、“模型别名与能力矩阵”，则 \`requirements.md\` 应包含 \`### 3.1. 统一模型 API 网关\`、\`### 3.2. Provider Adapter 接入框架\`、\`### 3.3. 模型别名与能力矩阵\`，每个小节下都包含 \`功能概述\`、\`改造范围\`、\`验收标准\`、\`技术方案\`、\`风险与应对措施\`。
   - \`4.4. 业务性能需求描述\` 必须作为 \`requirements.md\` 的最后一个小节，并使用固定 Markdown 表格输出；表格列为 \`性能类型\`、\`性能需求描述\`，行必须包含 \`业务处理性能\`、\`业务容量\`、\`业务响应时间\`、\`日终批处理能力\`。
   - 如果原始 requirement 明确给出性能指标，将指标写入对应表格单元格，例如 \`业务响应时间\` 可写 \`响应延迟 <= 60s\`；如果未明确，则对应单元格写 \`本次未明确\`，不要删除表格行。
   - 本步骤的唯一需求产物是 \`infraspec/changes/<name>/requirements.md\`；所有子功能内容均以内嵌章节形式写入该文件。

7. **STOP，等待用户下一步指示**
   在这一步不要创建 proposal.md、specs、design.md 或 tasks.md。

**Output**

完成以上步骤后，输出总结：
- Change name 和所在位置
- Requirement description 文件位置
- Code context 文件位置
- Requirements 文件位置
- \`requirements.md\` 中保存了什么
- Prompt: "Run \`/infra:review <name>\` to generate the lean-process detailed design specification (\`detailed-design.md\`)."

**Guardrails**
- 现在还不要创建任何正式的 InfraSpec artifacts
- 在这一步不要展示第一个 artifact template
- 不要推进到保存 \`requirements.md\` 之后的阶段
- \`requirements.md\` 是本步骤唯一需求文档；所有子功能详情均写入 \`3. 功能详情\`
- 不要让用户手动运行 \`infraspec code analyze\`；这是 workflow 内部自动步骤
- 如果代码图谱分析失败，必须保留 \`code-context.md\` 中的失败说明，并继续生成 \`requirements.md\`
- 如果 name 非法（不是 kebab-case），要求用户提供合法名称
- 如果同名 change 已存在，建议用户改用 \`/infra:review\`
- 如果使用非默认 workflow，记得传入 \`--schema\``
  };
}
