/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getNewChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'infra-new-change',
    description: '使用实验性的 artifact workflow 启动一个新的 InfraSpec change。适用于用户想以结构化、分步骤的方式创建新功能、修复问题或做修改的场景。',
    instructions: `使用实验性的 artifact-driven 方式启动一个新的 change。

**Input**: 用户请求中应包含 change name（kebab-case），或者描述其想要构建内容的 requirement 内容。该 requirement 内容也可能是已经从其他格式预处理后的纯文本需求文档。

**Steps**

1. **如果没有清晰输入，先询问用户要构建什么**

   使用 **AskUserQuestion tool**（开放式提问，不提供预设选项）询问：
   > "What change do you want to work on? Describe the requirement or paste the requirement document text."

   根据用户描述推导出一个 kebab-case name（例如 "add user authentication" → \`add-user-auth\`）。

   **IMPORTANT**: 在理解 requirement 内容之前，不要继续。

2. **确定 workflow schema**

   默认使用默认 schema（即省略 \`--schema\`），除非用户明确要求使用其他 workflow。

   **只有在用户提到以下情况时，才使用非默认 schema：**
   - 明确给出某个 schema name → 使用 \`--schema <name>\`
   - 提到 "show workflows" 或 "what workflows" → 运行 \`infraspec schemas --json\` 并让用户选择

   **Otherwise**: 省略 \`--schema\`，使用默认 workflow。

3. **创建 change 目录**
   \`\`\`bash
   infraspec new change "<name>"
   \`\`\`
   只有在用户要求特定 workflow 时才附加 \`--schema <name>\`。
   这会在 InfraSpec workspace 的 \`infraspec/changes/<name>/\` 下，用所选 schema 创建一个脚手架化的 change。

4. **保存原始需求描述**
   将用户提供的原始 requirement 输入保存到：
   \`infraspec/changes/<name>/requirement-description.md\`

   写作规则：
   - 尽量保留用户原始表达，不要提前改写成正式需求文档。
   - 如果用户粘贴的是长文档，也完整保存。
   - 后续所有分析都以该文件作为需求输入源。

5. **运行代码图谱分析**
   这是 workflow 的自动尝试步骤，由当前 AI agent 自动运行，不要要求用户手动执行该命令。
   在创建 \`requirements.md\` 前，必须先尝试运行：
   \`\`\`bash
   infraspec code analyze --change "<name>" --json
   \`\`\`

   该命令会读取 \`requirement-description.md\`，并生成：
   - \`infraspec/changes/<name>/code-context.md\`：代码上下文摘要
   - \`infraspec/changes/<name>/.code-context.json\`：结构化代码上下文

   如果命令执行失败、命令不可用，或返回 \`status: "unavailable"\`，不要中断 \`/infra:new\`；降级跳过代码图谱分析并继续创建 \`requirements.md\`，但在代码相关章节中明确说明代码图谱分析不可用。

   **Fallback gate**: 继续前应尽量确认 \`infraspec/changes/<name>/code-context.md\` 已存在。
   - 如果文件不存在，重新运行一次 \`infraspec code analyze --change "<name>" --json\`。
   - 如果仍然失败，手动写入一个降级版 \`code-context.md\`，说明代码图谱分析不可用及失败原因，然后继续。
   - 不允许因为代码图谱分析失败而阻止生成 \`requirements.md\`。

6. **创建 \`requirements.md\`**
   读取：
   - \`infraspec/changes/<name>/requirement-description.md\`
   - \`infraspec/changes/<name>/code-context.md\`

   将用户的 requirement 输入和代码图谱分析结果整理成以下精确的公司结构：
   - \`# 需求文档\`
   - \`## 1. 需求概述\`
   - \`### 1.1 背景、目标及价值（必填）\`
   - \`### 1.2 关键指标（必填）\`
   - \`### 1.3 术语名词解释（选填）\`
   - \`## 2. 需求解析\`
   - \`### 2.1 现状分析（选填）\`
   - \`### 2.2 方案设计（选填）\`
   - \`### 2.3 功能清单（必填）\`
   - \`## 3. 影响分析\`
   - \`### 3.1 依赖评估（选填）\`
   - \`### 3.2 影响评估（选填）\`
   - \`### 3.3 安全评估（选填）\`

   写作规则：
   - 保留用户原始表达的真实含义。
   - 严格使用公司要求的章节顺序。
   - 所有必填章节都要写出有实质内容的内容。
   - \`2.1 现状分析\`、\`2.2 方案设计\`、\`3.1 依赖评估\`、\`3.2 影响评估\` 应优先使用 \`code-context.md\` 中的代码事实、相关模块、入口符号和影响线索。
   - 选填章节如果 requirement 或 code-context 支持则填写；否则明确写 \`本次未明确\`。
   - 如果关键信息缺失，写 \`待确认事项\`，不要编造事实。
   - 在 \`2.3 功能清单\` 中，使用稳定标识符，例如 \`F1\`、\`F2\`、\`F3\`。

7. **STOP，等待用户下一步指示**
   在这一步不要创建 proposal.md、specs、design.md 或 tasks.md。

**Output**

完成以上步骤后，输出总结：
- Change name 和所在位置
- Requirement description 文件位置
- Code context 文件位置
- Requirements 文件位置
- \`requirements.md\` 中保存了什么
- Prompt: "Run \`/infra:review <name>\` to generate the lean-process detailed design specification (\`detailed-design.md\`)."

**Guardrails**
- 现在还不要创建任何正式的 InfraSpec artifacts
- 在这一步不要展示第一个 artifact template
- 不要推进到保存 \`requirements.md\` 之后的阶段
- 不要让用户手动运行 \`infraspec code analyze\`；这是 workflow 内部自动步骤
- 如果代码图谱分析失败，必须保留 \`code-context.md\` 中的失败说明，并继续生成 \`requirements.md\`
- 如果 name 非法（不是 kebab-case），要求用户提供合法名称
- 如果同名 change 已存在，建议用户继续该 change，而不是新建
- 如果使用非默认 workflow，记得传入 \`--schema\``,
    compatibility: 'Requires InfraSpec CLI (`infraspec`).',
    metadata: { author: 'bianyongmei', version: '1.0' },
  };
}

export function getOpsxNewCommandTemplate(): CommandTemplate {
  return {
    name: 'INFRA: New',
    description: '使用实验性的 artifact workflow 启动一个新的 change（INFRA）',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `使用实验性的 artifact-driven 方式启动一个新的 change。

**Input**: \`/infra:new\` 后的参数可以是 change name（kebab-case），或者描述用户想构建内容的 requirement 内容。该 requirement 内容也可能是已经从其他格式预处理后的纯文本需求文档。

**Steps**

1. **如果没有提供输入，先询问用户要构建什么**

   使用 **AskUserQuestion tool**（开放式提问，不提供预设选项）询问：
   > "What change do you want to work on? Describe the requirement or paste the requirement document text."

   根据用户描述推导出一个 kebab-case name（例如 "add user authentication" → \`add-user-auth\`）。

   **IMPORTANT**: 在理解 requirement 内容之前，不要继续。

2. **确定 workflow schema**

   默认使用默认 schema（即省略 \`--schema\`），除非用户明确要求使用其他 workflow。

   **只有在用户提到以下情况时，才使用非默认 schema：**
   - 明确给出某个 schema name → 使用 \`--schema <name>\`
   - 提到 "show workflows" 或 "what workflows" → 运行 \`infraspec schemas --json\` 并让用户选择

   **Otherwise**: 省略 \`--schema\`，使用默认 workflow。

3. **创建 change 目录**
   \`\`\`bash
   infraspec new change "<name>"
   \`\`\`
   只有在用户要求特定 workflow 时才附加 \`--schema <name>\`。
   这会在 InfraSpec workspace 的 \`infraspec/changes/<name>/\` 下，用所选 schema 创建一个脚手架化的 change。

4. **保存原始需求描述**
   将用户提供的原始 requirement 输入保存到：
   \`infraspec/changes/<name>/requirement-description.md\`

   写作规则：
   - 尽量保留用户原始表达，不要提前改写成正式需求文档。
   - 如果用户粘贴的是长文档，也完整保存。
   - 后续所有分析都以该文件作为需求输入源。

5. **运行代码图谱分析**
   这是 workflow 的自动尝试步骤，由当前 AI agent 自动运行，不要要求用户手动执行该命令。
   在创建 \`requirements.md\` 前，必须先尝试运行：
   \`\`\`bash
   infraspec code analyze --change "<name>" --json
   \`\`\`

   该命令会读取 \`requirement-description.md\`，并生成：
   - \`infraspec/changes/<name>/code-context.md\`：代码上下文摘要
   - \`infraspec/changes/<name>/.code-context.json\`：结构化代码上下文

   如果命令执行失败、命令不可用，或返回 \`status: "unavailable"\`，不要中断 \`/infra:new\`；降级跳过代码图谱分析并继续创建 \`requirements.md\`，但在代码相关章节中明确说明代码图谱分析不可用。

   **Fallback gate**: 继续前应尽量确认 \`infraspec/changes/<name>/code-context.md\` 已存在。
   - 如果文件不存在，重新运行一次 \`infraspec code analyze --change "<name>" --json\`。
   - 如果仍然失败，手动写入一个降级版 \`code-context.md\`，说明代码图谱分析不可用及失败原因，然后继续。
   - 不允许因为代码图谱分析失败而阻止生成 \`requirements.md\`。

6. **创建 \`requirements.md\`**
   读取：
   - \`infraspec/changes/<name>/requirement-description.md\`
   - \`infraspec/changes/<name>/code-context.md\`

   将用户的 requirement 输入和代码图谱分析结果整理成以下精确的公司结构：
   - \`# 需求文档\`
   - \`## 1. 需求概述\`
   - \`### 1.1 背景、目标及价值（必填）\`
   - \`### 1.2 关键指标（必填）\`
   - \`### 1.3 术语名词解释（选填）\`
   - \`## 2. 需求解析\`
   - \`### 2.1 现状分析（选填）\`
   - \`### 2.2 方案设计（选填）\`
   - \`### 2.3 功能清单（必填）\`
   - \`## 3. 影响分析\`
   - \`### 3.1 依赖评估（选填）\`
   - \`### 3.2 影响评估（选填）\`
   - \`### 3.3 安全评估（选填）\`

   写作规则：
   - 保留用户原始表达的真实含义。
   - 严格使用公司要求的章节顺序。
   - 所有必填章节都要写出有实质内容的内容。
   - \`2.1 现状分析\`、\`2.2 方案设计\`、\`3.1 依赖评估\`、\`3.2 影响评估\` 应优先使用 \`code-context.md\` 中的代码事实、相关模块、入口符号和影响线索。
   - 选填章节如果 requirement 或 code-context 支持则填写；否则明确写 \`本次未明确\`。
   - 如果关键信息缺失，写 \`待确认事项\`，不要编造事实。
   - 在 \`2.3 功能清单\` 中，使用稳定标识符，例如 \`F1\`、\`F2\`、\`F3\`。

7. **STOP，等待用户下一步指示**
   在这一步不要创建 proposal.md、specs、design.md 或 tasks.md。

**Output**

完成以上步骤后，输出总结：
- Change name 和所在位置
- Requirement description 文件位置
- Code context 文件位置
- Requirements 文件位置
- \`requirements.md\` 中保存了什么
- Prompt: "Run \`/infra:review <name>\` to generate the lean-process detailed design specification (\`detailed-design.md\`)."

**Guardrails**
- 现在还不要创建任何正式的 InfraSpec artifacts
- 在这一步不要展示第一个 artifact template
- 不要推进到保存 \`requirements.md\` 之后的阶段
- 不要让用户手动运行 \`infraspec code analyze\`；这是 workflow 内部自动步骤
- 如果代码图谱分析失败，必须保留 \`code-context.md\` 中的失败说明，并继续生成 \`requirements.md\`
- 如果 name 非法（不是 kebab-case），要求用户提供合法名称
- 如果同名 change 已存在，建议用户改用 \`/infra:review\`
- 如果使用非默认 workflow，记得传入 \`--schema\``
  };
}
