/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getOpsxProposeSkillTemplate(): SkillTemplate {
  return {
    name: 'infra-propose',
    description: 'Propose a new change with all artifacts generated in one step. Use when the user wants to quickly describe what they want to build and get a complete proposal with design, specs, and tasks ready for implementation.',
    instructions: `Propose a new change - create the change and generate all artifacts in one step.

I'll create a change with artifacts:
- proposal.md (what & why)
- design.md (how)
- tasks.md (implementation steps)

When ready to implement, run /infra:apply

---

**Input**: The user's request should include a change name (kebab-case) OR a description of what they want to build.

**Steps**

1. **If no clear input provided, ask what they want to build**

   Use the **AskUserQuestion tool** (open-ended, no preset options) to ask:
   > "What change do you want to work on? Describe what you want to build or fix."

   From their description, derive a kebab-case name (e.g., "add user authentication" → \`add-user-auth\`).

   If the user provides only a change name and no requirement description can be inferred from the conversation, ask them to describe the change before continuing. A name alone is not sufficient input for code graph analysis.

   **IMPORTANT**: Do NOT proceed without both a change name and enough requirement content to understand what the user wants to build.

2. **Create the change directory**
   \`\`\`bash
   infraspec new change "<name>"
   \`\`\`
   This creates a scaffolded change in the InfraSpec workspace at \`infraspec/changes/<name>/\` with \`.infraspec.yaml\`.

3. **Save the original requirement description**

   Save the user's original requirement input to:
   \`infraspec/changes/<name>/requirement-description.md\`

   Preserve the user's original meaning and detail. Do not rewrite it into proposal format yet; this file is the stable query source for code graph analysis and later workflow refreshes.

4. **Generate and read code graph context**

   This is an internal workflow step. Run it automatically; do not ask the user to run it:

   \`\`\`bash
   infraspec code analyze --change "<name>" --json
   \`\`\`

   The command reads \`requirement-description.md\` and generates:
   - \`infraspec/changes/<name>/code-context.md\`: compact code context for people and agents
   - \`infraspec/changes/<name>/.code-context.json\`: structured analysis details

   Read \`code-context.md\` before creating artifacts. Use it as code-fact context for existing modules, entry symbols, related files, dependencies, and potential impact.

   If code analysis fails, do not block proposal generation:
   - If an existing \`code-context.md\` is present, read it and continue.
   - If it is missing, continue with the requirement and artifact dependencies, and clearly mark unsupported code facts as assumptions or items to confirm.

   Do not read \`infraspec/.code-graph/index.json\` or \`.code-context.json\` by default; use the compact \`code-context.md\`.

5. **Get the artifact build order**
   \`\`\`bash
   infraspec status --change "<name>" --json
   \`\`\`
   Parse the JSON to get:
   - \`applyRequires\`: array of artifact IDs needed before implementation (e.g., \`["tasks"]\`)
   - \`artifacts\`: list of all artifacts with their status and dependencies

6. **Create artifacts in sequence until apply-ready**

   Use the **TodoWrite tool** to track progress through the artifacts.

   Loop through artifacts in dependency order (artifacts with no pending dependencies first):

   a. **For each artifact that is \`ready\` (dependencies satisfied)**:
      - Get instructions:
        \`\`\`bash
        infraspec instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - The instructions JSON includes:
        - \`context\`: Project background (constraints for you - do NOT include in output)
        - \`rules\`: Artifact-specific rules (constraints for you - do NOT include in output)
        - \`template\`: The structure to use for your output file
        - \`instruction\`: Schema-specific guidance for this artifact type
        - \`outputPath\`: Where to write the artifact
        - \`dependencies\`: Completed artifacts to read for context
      - Read any completed dependency files for context
      - Read \`code-context.md\` as the code-fact context when it is available
      - Create the artifact file using \`template\` as the structure
      - Apply \`context\` and \`rules\` as constraints - but do NOT copy them into the file
      - Ground code-related claims in \`code-context.md\`; mark anything it cannot establish as an assumption or item to confirm
      - Show brief progress: "Created <artifact-id>"

   b. **Continue until all \`applyRequires\` artifacts are complete**
      - After creating each artifact, re-run \`infraspec status --change "<name>" --json\`
      - Check if every artifact ID in \`applyRequires\` has \`status: "done"\` in the artifacts array
      - Stop when all \`applyRequires\` artifacts are done

   c. **If an artifact requires user input** (unclear context):
      - Use **AskUserQuestion tool** to clarify
      - Then continue with creation

7. **Show final status**
   \`\`\`bash
   infraspec status --change "<name>"
   \`\`\`

**Output**

After completing all artifacts, summarize:
- Change name and location
- List of artifacts created with brief descriptions
- What's ready: "All artifacts created! Ready for implementation."
- Prompt: "Run \`/infra:apply\` or ask me to implement to start working on the tasks."

**Artifact Creation Guidelines**

- Follow the \`instruction\` field from the InfraSpec CLI (\`infraspec instructions\`) for each artifact type
- The schema defines what each artifact should contain - follow it
- Read dependency artifacts for context before creating new ones
- Read \`code-context.md\` before artifact creation and use it as the source for code facts
- For \`proposal.md\`, use code context to support scope and impact; for \`design.md\`, use entry symbols, related files, and dependencies; for \`tasks.md\`, map work to likely files, symbols, and verification points
- Use \`template\` as the structure for your output file - fill in its sections
- **IMPORTANT**: \`context\` and \`rules\` are constraints for YOU, not content for the file
  - Do NOT copy \`<context>\`, \`<rules>\`, \`<project_context>\` blocks into the artifact
  - These guide what you write, but should never appear in the output

**Guardrails**
- Create ALL artifacts needed for implementation (as defined by schema's \`apply.requires\`)
- Always preserve the original requirement in \`requirement-description.md\` before running code analysis
- Attempt code graph analysis before creating artifacts, but do not block the workflow if it is unavailable
- Always read dependency artifacts before creating a new one
- If context is critically unclear, ask the user - but prefer making reasonable decisions to keep momentum
- If a change with that name already exists, ask if user wants to continue it or create a new one
- Verify each artifact file exists after writing before proceeding to next`,
    compatibility: 'Requires InfraSpec CLI (`infraspec`).',
    metadata: { author: 'bianyongmei', version: '1.0' },
  };
}

export function getOpsxProposeCommandTemplate(): CommandTemplate {
  return {
    name: 'INFRA: Propose',
    description: 'Propose a new change - create it and generate all artifacts in one step',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `Propose a new change - create the change and generate all artifacts in one step.

I'll create a change with artifacts:
- proposal.md (what & why)
- design.md (how)
- tasks.md (implementation steps)

When ready to implement, run /infra:apply

---

**Input**: The argument after \`/infra:propose\` is the change name (kebab-case), OR a description of what the user wants to build.

**Steps**

1. **If no input provided, ask what they want to build**

   Use the **AskUserQuestion tool** (open-ended, no preset options) to ask:
   > "What change do you want to work on? Describe what you want to build or fix."

   From their description, derive a kebab-case name (e.g., "add user authentication" → \`add-user-auth\`).

   If the user provides only a change name and no requirement description can be inferred from the conversation, ask them to describe the change before continuing. A name alone is not sufficient input for code graph analysis.

   **IMPORTANT**: Do NOT proceed without both a change name and enough requirement content to understand what the user wants to build.

2. **Create the change directory**
   \`\`\`bash
   infraspec new change "<name>"
   \`\`\`
   This creates a scaffolded change in the InfraSpec workspace at \`infraspec/changes/<name>/\` with \`.infraspec.yaml\`.

3. **Save the original requirement description**

   Save the user's original requirement input to:
   \`infraspec/changes/<name>/requirement-description.md\`

   Preserve the user's original meaning and detail. Do not rewrite it into proposal format yet; this file is the stable query source for code graph analysis and later workflow refreshes.

4. **Generate and read code graph context**

   This is an internal workflow step. Run it automatically; do not ask the user to run it:

   \`\`\`bash
   infraspec code analyze --change "<name>" --json
   \`\`\`

   The command reads \`requirement-description.md\` and generates:
   - \`infraspec/changes/<name>/code-context.md\`: compact code context for people and agents
   - \`infraspec/changes/<name>/.code-context.json\`: structured analysis details

   Read \`code-context.md\` before creating artifacts. Use it as code-fact context for existing modules, entry symbols, related files, dependencies, and potential impact.

   If code analysis fails, do not block proposal generation:
   - If an existing \`code-context.md\` is present, read it and continue.
   - If it is missing, continue with the requirement and artifact dependencies, and clearly mark unsupported code facts as assumptions or items to confirm.

   Do not read \`infraspec/.code-graph/index.json\` or \`.code-context.json\` by default; use the compact \`code-context.md\`.

5. **Get the artifact build order**
   \`\`\`bash
   infraspec status --change "<name>" --json
   \`\`\`
   Parse the JSON to get:
   - \`applyRequires\`: array of artifact IDs needed before implementation (e.g., \`["tasks"]\`)
   - \`artifacts\`: list of all artifacts with their status and dependencies

6. **Create artifacts in sequence until apply-ready**

   Use the **TodoWrite tool** to track progress through the artifacts.

   Loop through artifacts in dependency order (artifacts with no pending dependencies first):

   a. **For each artifact that is \`ready\` (dependencies satisfied)**:
      - Get instructions:
        \`\`\`bash
        infraspec instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - The instructions JSON includes:
        - \`context\`: Project background (constraints for you - do NOT include in output)
        - \`rules\`: Artifact-specific rules (constraints for you - do NOT include in output)
        - \`template\`: The structure to use for your output file
        - \`instruction\`: Schema-specific guidance for this artifact type
        - \`outputPath\`: Where to write the artifact
        - \`dependencies\`: Completed artifacts to read for context
      - Read any completed dependency files for context
      - Read \`code-context.md\` as the code-fact context when it is available
      - Create the artifact file using \`template\` as the structure
      - Apply \`context\` and \`rules\` as constraints - but do NOT copy them into the file
      - Ground code-related claims in \`code-context.md\`; mark anything it cannot establish as an assumption or item to confirm
      - Show brief progress: "Created <artifact-id>"

   b. **Continue until all \`applyRequires\` artifacts are complete**
      - After creating each artifact, re-run \`infraspec status --change "<name>" --json\`
      - Check if every artifact ID in \`applyRequires\` has \`status: "done"\` in the artifacts array
      - Stop when all \`applyRequires\` artifacts are done

   c. **If an artifact requires user input** (unclear context):
      - Use **AskUserQuestion tool** to clarify
      - Then continue with creation

7. **Show final status**
   \`\`\`bash
   infraspec status --change "<name>"
   \`\`\`

**Output**

After completing all artifacts, summarize:
- Change name and location
- List of artifacts created with brief descriptions
- What's ready: "All artifacts created! Ready for implementation."
- Prompt: "Run \`/infra:apply\` to start implementing."

**Artifact Creation Guidelines**

- Follow the \`instruction\` field from the InfraSpec CLI (\`infraspec instructions\`) for each artifact type
- The schema defines what each artifact should contain - follow it
- Read dependency artifacts for context before creating new ones
- Read \`code-context.md\` before artifact creation and use it as the source for code facts
- For \`proposal.md\`, use code context to support scope and impact; for \`design.md\`, use entry symbols, related files, and dependencies; for \`tasks.md\`, map work to likely files, symbols, and verification points
- Use \`template\` as the structure for your output file - fill in its sections
- **IMPORTANT**: \`context\` and \`rules\` are constraints for YOU, not content for the file
  - Do NOT copy \`<context>\`, \`<rules>\`, \`<project_context>\` blocks into the artifact
  - These guide what you write, but should never appear in the output

**Guardrails**
- Create ALL artifacts needed for implementation (as defined by schema's \`apply.requires\`)
- Always preserve the original requirement in \`requirement-description.md\` before running code analysis
- Attempt code graph analysis before creating artifacts, but do not block the workflow if it is unavailable
- Always read dependency artifacts before creating a new one
- If context is critically unclear, ask the user - but prefer making reasonable decisions to keep momentum
- If a change with that name already exists, ask if user wants to continue it or create a new one
- Verify each artifact file exists after writing before proceeding to next`
  };
}
