/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getReviewChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'infra-review-change',
    description: '在创建下一个 artifact 前先 review 当前变更。适用于用户想查看变更进度、创建下一个 artifact，或通过 review 命令继续工作流的场景。',
    instructions: `通过创建下一个 artifact 来继续推进一个 change。

**Input**: 可以可选地指定 change name。如果未指定，先检查是否能从当前对话上下文中推断；如果不明确或有歧义，你 MUST 提示用户从可用 changes 中选择。

**Steps**

1. **如果没有提供 change name，提示用户进行选择**

   运行 \`infraspec list --json\` 获取可用 changes，并按最近修改时间排序。然后使用 **AskUserQuestion tool** 让用户选择要继续处理的 change。

   将最近修改的 3-4 个 changes 作为选项展示，并包含：
   - Change name
   - Schema（如果存在 \`schema\` 字段则显示其值，否则显示 "spec-driven"）
   - Status（例如 "0/5 tasks"、"complete"、"no tasks"）
   - 最近一次修改时间（来自 \`lastModified\` 字段）

   将最近修改的 change 标记为 "(Recommended)"，因为它最可能是用户想继续处理的对象。

   **IMPORTANT**: 不要猜测，也不要自动替用户选择 change。必须让用户自己选。

2. **检查当前状态**
   在进入 artifact workflow 之前，先检查本 review 流程要求的两个 pre-spec 文档是否已经存在：
   - \`infraspec/changes/<name>/requirements.md\`
   - \`infraspec/changes/<name>/detailed-design.md\`

   固定的 review 流程为：
   \`requirements -> detailed-design -> proposal -> specs/design -> tasks\`

   先处理这两个 pre-spec 文档：

   - If \`requirements.md\` does not exist:
     - 根据用户提供的需求文档，或当前对话里最可靠的需求上下文来创建它。
     - 如果需求存在歧义或信息不完整，先向用户确认，再进行写入。
     - 保存到 \`infraspec/changes/<name>/requirements.md\`。
     - 只创建这个文件后就 STOP。

   - If \`requirements.md\` exists but \`detailed-design.md\` does not:
     - 读取 \`requirements.md\`。
     - 按公司要求的详细设计文档格式创建 \`detailed-design.md\`。
     - 使用 Markdown 生成，并严格遵循以下章节顺序：
       - \`# 详细设计文档\`
       - \`## 1. 引言\`
       - \`### 1.1 目的\`
       - \`### 1.2 统一术语\`
       - \`## 2. 应用架构详细设计\`
       - \`### 2.1 接口设计\`
       - \`#### 2.1.1 <接口名称> 接口\`
       - \`### 2.2 业务功能的流程设计\`
       - \`#### 2.2.1 <功能名称> 功能流程设计\`
       - \`### 2.3 领域模型设计（可选）\`
       - \`#### 2.3.1 <实体名称> 实体设计\`
       - \`### 2.4 持久化模型设计（可选）\`
       - \`#### 2.4.1 <持久化模型名称> 持久化模型设计\`
       - \`### 2.5 技术参数变更的流程设计（可选）\`
       - \`#### 2.5.1 <参数或流程名称> 流程设计\`
       - \`## 3. 系统架构详细设计\`
       - \`### 3.1 数据库详细设计\`
       - \`#### 3.1.1 数据库表设计\`
       - \`#### 3.1.2 数据库索引设计\`
       - \`### 3.2 云服务落地方案\`
       - \`#### 3.2.1 <云服务名称> 云服务\`
     - 章节要求：
       - 接口设计 MUST 覆盖 purpose、caller/callee、method/path、request params、response、error handling 和 security/auth。
       - 业务流程设计 MUST 覆盖 goal、preconditions、main flow、exception flow、inputs/outputs 和 flow notes。
       - 可选章节 MUST 要么写出具体内容，要么明确写 \`本次不涉及\`。
       - 如果没有 schema/index 变更，数据库设计 MUST 明确写 \`本次不涉及\`。
       - 如果没有云资源变更，云服务设计 MUST 明确写 \`本次不涉及\`。
     - 生成规则：
       - 先以 \`requirements.md\` 为基础，再在必要时做合理的工程推断。
       - 将所有占位符替换成具体名称。
       - 不要输出空白大纲。
       - 如果需求信息不足，将缺失部分标记为 \`待确认事项\`，不要编造事实。
     - 保存到 \`infraspec/changes/<name>/detailed-design.md\`。
     - 只创建这个文件后就 STOP。

   - 只有在这两个文件都存在之后，才继续下面已有的 artifact workflow。

   然后检查当前 InfraSpec artifact 状态：
   \`\`\`bash
   infraspec status --change "<name>" --json
   \`\`\`
   解析 JSON 以理解当前状态。返回内容包括：
   - \`schemaName\`：当前使用的 workflow schema（例如 "spec-driven"）
   - \`artifacts\`：artifact 数组，以及每个 artifact 的状态（"done"、"ready"、"blocked"）
   - \`isComplete\`：布尔值，表示所有 artifacts 是否都已完成

3. **根据状态执行相应动作**：

   ---

   **如果所有 artifacts 都已完成（\`isComplete: true\`）**：
   - 祝贺用户
   - 展示最终状态，并带上当前使用的 schema
   - 提示："All artifacts created! You can now implement this change or archive it."
   - STOP

   ---

   **如果存在可创建的 artifacts**（状态中有 \`status: "ready"\` 的 artifact）：
   - 从状态输出中选择第一个 \`status: "ready"\` 的 artifact
   - 获取它的 instructions：
     \`\`\`bash
     infraspec instructions <artifact-id> --change "<name>" --json
     \`\`\`
   - 解析 JSON。关键字段包括：
     - \`context\`：项目背景（这是给你的约束，不要出现在输出文件里）
     - \`rules\`：artifact 专属规则（这是给你的约束，不要出现在输出文件里）
     - \`template\`：输出文件应采用的结构
     - \`instruction\`：schema 专属指导
     - \`outputPath\`：artifact 的写入路径
     - \`dependencies\`：创建前需要读取的已完成 artifacts
   - **创建 artifact 文件**：
     - 读取已完成的 dependency 文件作为上下文
     - 以 \`template\` 作为结构，填写对应章节内容
     - 在写作时应用 \`context\` 和 \`rules\` 作为约束，但不要把它们原样复制进文件
     - 按 instructions 指定的 \`outputPath\` 写入
   - 展示已创建的内容，以及因此解锁了哪些后续 artifact
   - 只创建一个 artifact 后就 STOP

   ---

   **如果没有任何 artifact 可创建（全部 blocked）**：
   - 这在有效 schema 下通常不应该发生
   - 展示当前状态，并建议检查是否存在异常问题

4. **创建 artifact 后，展示进度**
   \`\`\`bash
   infraspec status --change "<name>"
   \`\`\`

**Output**

每次执行后，都要展示：
- 刚创建的是哪个 artifact
- 当前使用的 schema workflow
- 当前进度（N/M complete）
- 现在又解锁了哪些 artifacts
- Prompt：点名刚创建的 artifact，以及下一个 ready 的 artifact，并在命令里显式带上当前 change name
  - 示例："You can now review \`<created-artifact>\` and then run \`/infra:review <name>\` again to create the next artifact (\`design\` or \`specs\`)."

对于这两个 pre-spec 文档：
- \`requirements.md\`：从用户的需求文档中提炼出的 requirements
- \`detailed-design.md\`：基于 \`requirements.md\` 生成的公司格式详细设计
- 在进入 proposal/specs/design/tasks 之前，这两个文件在 review 流程中是必需前置项
- 即使后续 InfraSpec status 输出仍只跟踪 schema 中原有的 artifacts，这两个文件仍然属于 review flow 的组成部分

**Artifact Creation Guidelines**

artifact 的类型和用途取决于 schema。使用 instructions 输出里的 \`instruction\` 字段来理解当前应该创建什么。

常见 artifact 模式：

**review pre-spec documents**：
- **requirements.md**：以简洁、可直接用于实现的方式承接用户的需求文档。保留 scope、constraints、actors、inputs/outputs 和 acceptance expectations。
- **detailed-design.md**：基于 \`requirements.md\` 生成公司要求的详细设计文档，并严格遵循公司规定结构。
  - Required structure：
    - \`1. 引言\` → \`1.1 目的\`, \`1.2 统一术语\`
    - \`2. 应用架构详细设计\` → \`2.1 接口设计\`, \`2.2 业务功能的流程设计\`, \`2.3 领域模型设计（可选）\`, \`2.4 持久化模型设计（可选）\`, \`2.5 技术参数变更的流程设计（可选）\`
    - \`3. 系统架构详细设计\` → \`3.1 数据库详细设计\`, \`3.2 云服务落地方案\`
  - 可选章节在不适用时必须明确写 \`本次不涉及\`。
  - 未知细节必须标记为 \`待确认事项\`。

**spec-driven schema**（proposal → specs → design → tasks）：
- **proposal.md**：以 \`detailed-design.md\` 为基础，填写 Why、What Changes、Capabilities、Impact。
  - Capabilities 章节非常关键，其中列出的每个 capability 都需要对应一个 spec file。
- **specs/<capability>/spec.md**：为 proposal 的 Capabilities 章节中列出的每个 capability 创建一个 spec（使用 capability 名，而不是 change 名）。
- **design.md**：创建一个面向实现的技术设计文档，综合 \`proposal.md\`、\`specs\` 以及（如果存在）\`detailed-design.md\`。
  - 如果 \`detailed-design.md\` 存在，在生成 \`design.md\` 前 MUST 先读取它。
  - 保留会影响实现的关键细节，例如接口约束、关键流程、持久化/数据库变更、外部依赖、安全限制和 rollout 要求。
  - 不要机械复制 \`detailed-design.md\` 的公司格式标题；应将内容重组到 \`design.md\` 模板结构中。
- **tasks.md**：将实现工作拆分为带 checkbox 的任务列表。

对于其他 schemas，遵循 CLI 输出中的 \`instruction\` 字段。

**Guardrails**
- 每次调用只创建 ONE artifact
- 在 review 中，\`requirements.md\` 和 \`detailed-design.md\` 必须作为 \`proposal.md\` 之前的前置项
- 创建新 artifact 前始终先读取 dependency artifacts
- 不要跳过 artifact，也不要乱序创建
- 如果上下文不清楚，先向用户确认，再创建
- 写入后先确认 artifact 文件确实存在，再汇报进度
- 遵循 schema 定义的 artifact 顺序，不要自行假设固定 artifact 名称
- **IMPORTANT**：\`context\` 和 \`rules\` 是给你的约束，不是文件内容
  - 不要把 \`<context>\`、\`<rules>\`、\`<project_context>\` 这些块复制进 artifact
  - 它们只用于指导你写什么，不应直接出现在输出中`,
    license: 'MIT',
    compatibility: 'Requires InfraSpec CLI (`infraspec`).',
    metadata: { author: 'bianyongmei', version: '1.0' },
  };
}

export function getOpsxReviewCommandTemplate(): CommandTemplate {
  return {
    name: 'INFRA: Review',
    description: 'Review 一个 change，并创建下一个 artifact（Experimental）',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `通过创建下一个 artifact 来继续推进一个 change。

**Input**: 可以在 \`/infra:review\` 后可选指定 change name（例如 \`/infra:review add-auth\`）。如果未指定，先检查是否能从当前对话上下文中推断；如果不明确或有歧义，你 MUST 提示用户从可用 changes 中选择。

**Steps**

1. **如果没有提供 change name，提示用户进行选择**

   运行 \`infraspec list --json\` 获取可用 changes，并按最近修改时间排序。然后使用 **AskUserQuestion tool** 让用户选择要继续处理的 change。

   将最近修改的 3-4 个 changes 作为选项展示，并包含：
   - Change name
   - Schema（如果存在 \`schema\` 字段则显示其值，否则显示 "spec-driven"）
   - Status（例如 "0/5 tasks"、"complete"、"no tasks"）
   - 最近一次修改时间（来自 \`lastModified\` 字段）

   将最近修改的 change 标记为 "(Recommended)"，因为它最可能是用户想继续处理的对象。

   **IMPORTANT**: 不要猜测，也不要自动替用户选择 change。必须让用户自己选。

2. **检查当前状态**
   在进入 artifact workflow 之前，先检查本 review 流程要求的两个 pre-spec 文档是否已经存在：
   - \`infraspec/changes/<name>/requirements.md\`
   - \`infraspec/changes/<name>/detailed-design.md\`

   固定的 review 流程为：
   \`requirements -> detailed-design -> proposal -> specs/design -> tasks\`

   先处理这两个 pre-spec 文档：

   - If \`requirements.md\` does not exist:
     - 根据用户提供的需求文档，或当前对话里最可靠的需求上下文来创建它。
     - 如果需求存在歧义或信息不完整，先向用户确认，再进行写入。
     - 保存到 \`infraspec/changes/<name>/requirements.md\`。
     - 只创建这个文件后就 STOP。

   - If \`requirements.md\` exists but \`detailed-design.md\` does not:
     - 读取 \`requirements.md\`。
     - 按公司要求的详细设计文档格式创建 \`detailed-design.md\`。
     - 使用 Markdown 生成，并严格遵循以下章节顺序：
       - \`# 详细设计文档\`
       - \`## 1. 引言\`
       - \`### 1.1 目的\`
       - \`### 1.2 统一术语\`
       - \`## 2. 应用架构详细设计\`
       - \`### 2.1 接口设计\`
       - \`#### 2.1.1 <接口名称> 接口\`
       - \`### 2.2 业务功能的流程设计\`
       - \`#### 2.2.1 <功能名称> 功能流程设计\`
       - \`### 2.3 领域模型设计（可选）\`
       - \`#### 2.3.1 <实体名称> 实体设计\`
       - \`### 2.4 持久化模型设计（可选）\`
       - \`#### 2.4.1 <持久化模型名称> 持久化模型设计\`
       - \`### 2.5 技术参数变更的流程设计（可选）\`
       - \`#### 2.5.1 <参数或流程名称> 流程设计\`
       - \`## 3. 系统架构详细设计\`
       - \`### 3.1 数据库详细设计\`
       - \`#### 3.1.1 数据库表设计\`
       - \`#### 3.1.2 数据库索引设计\`
       - \`### 3.2 云服务落地方案\`
       - \`#### 3.2.1 <云服务名称> 云服务\`
     - 章节要求：
       - 接口设计 MUST 覆盖 purpose、caller/callee、method/path、request params、response、error handling 和 security/auth。
       - 业务流程设计 MUST 覆盖 goal、preconditions、main flow、exception flow、inputs/outputs 和 flow notes。
       - 可选章节 MUST 要么写出具体内容，要么明确写 \`本次不涉及\`。
       - 如果没有 schema/index 变更，数据库设计 MUST 明确写 \`本次不涉及\`。
       - 如果没有云资源变更，云服务设计 MUST 明确写 \`本次不涉及\`。
     - 生成规则：
       - 先以 \`requirements.md\` 为基础，再在必要时做合理的工程推断。
       - 将所有占位符替换成具体名称。
       - 不要输出空白大纲。
       - 如果需求信息不足，将缺失部分标记为 \`待确认事项\`，不要编造事实。
     - 保存到 \`infraspec/changes/<name>/detailed-design.md\`。
     - 只创建这个文件后就 STOP。

   - 只有在这两个文件都存在之后，才继续下面已有的 artifact workflow。

   然后检查当前 InfraSpec artifact 状态：
   \`\`\`bash
   infraspec status --change "<name>" --json
   \`\`\`
   解析 JSON 以理解当前状态。返回内容包括：
   - \`schemaName\`：当前使用的 workflow schema（例如 "spec-driven"）
   - \`artifacts\`：artifact 数组，以及每个 artifact 的状态（"done"、"ready"、"blocked"）
   - \`isComplete\`：布尔值，表示所有 artifacts 是否都已完成

3. **根据状态执行相应动作**：

   ---

   **如果所有 artifacts 都已完成（\`isComplete: true\`）**：
   - 祝贺用户
   - 展示最终状态，并带上当前使用的 schema
   - 提示："All artifacts created! You can now implement this change with \`/infra:apply\` or archive it with \`/infra:archive\`."
   - STOP

   ---

   **如果存在可创建的 artifacts**（状态中有 \`status: "ready"\` 的 artifact）：
   - 从状态输出中选择第一个 \`status: "ready"\` 的 artifact
   - 获取它的 instructions：
     \`\`\`bash
     infraspec instructions <artifact-id> --change "<name>" --json
     \`\`\`
   - 解析 JSON。关键字段包括：
     - \`context\`：项目背景（这是给你的约束，不要出现在输出文件里）
     - \`rules\`：artifact 专属规则（这是给你的约束，不要出现在输出文件里）
     - \`template\`：输出文件应采用的结构
     - \`instruction\`：schema 专属指导
     - \`outputPath\`：artifact 的写入路径
     - \`dependencies\`：创建前需要读取的已完成 artifacts
   - **创建 artifact 文件**：
     - 读取已完成的 dependency 文件作为上下文
     - 以 \`template\` 作为结构，填写对应章节内容
     - 在写作时应用 \`context\` 和 \`rules\` 作为约束，但不要把它们原样复制进文件
     - 按 instructions 指定的 \`outputPath\` 写入
   - 展示已创建的内容，以及因此解锁了哪些后续 artifact
   - 只创建一个 artifact 后就 STOP

   ---

   **如果没有任何 artifact 可创建（全部 blocked）**：
   - 这在有效 schema 下通常不应该发生
   - 展示当前状态，并建议检查是否存在异常问题

4. **创建 artifact 后，展示进度**
   \`\`\`bash
   infraspec status --change "<name>"
   \`\`\`

**Output**

每次执行后，都要展示：
- 刚创建的是哪个 artifact
- 当前使用的 schema workflow
- 当前进度（N/M complete）
- 现在又解锁了哪些 artifacts
- Prompt："Review the artifact manually and then run \`/infra:review <name>\` to create the next artifact"
  - 示例："You can now review \`<created-artifact>\` and then run \`/infra:review <name>\` again to create the next artifact (\`design\` or \`specs\`)."

对于这两个 pre-spec 文档：
- \`requirements.md\`：从用户的需求文档中提炼出的 requirements
- \`detailed-design.md\`：基于 \`requirements.md\` 生成的公司格式详细设计
- 在进入 proposal/specs/design/tasks 之前，这两个文件在 review 流程中是必需前置项
- 即使后续 InfraSpec status 输出仍只跟踪 schema 中原有的 artifacts，这两个文件仍然属于 review flow 的组成部分

**Artifact Creation Guidelines**

artifact 的类型和用途取决于 schema。使用 instructions 输出里的 \`instruction\` 字段来理解当前应该创建什么。

常见 artifact 模式：

**review pre-spec documents**：
- **requirements.md**：以简洁、可直接用于实现的方式承接用户的需求文档。保留 scope、constraints、actors、inputs/outputs 和 acceptance expectations。
- **detailed-design.md**：基于 \`requirements.md\` 生成公司要求的详细设计文档，并严格遵循公司规定结构。
  - Required structure：
    - \`1. 引言\` → \`1.1 目的\`, \`1.2 统一术语\`
    - \`2. 应用架构详细设计\` → \`2.1 接口设计\`, \`2.2 业务功能的流程设计\`, \`2.3 领域模型设计（可选）\`, \`2.4 持久化模型设计（可选）\`, \`2.5 技术参数变更的流程设计（可选）\`
    - \`3. 系统架构详细设计\` → \`3.1 数据库详细设计\`, \`3.2 云服务落地方案\`
  - 可选章节在不适用时必须明确写 \`本次不涉及\`。
  - 未知细节必须标记为 \`待确认事项\`。

**spec-driven schema**（proposal → specs → design → tasks）：
- **proposal.md**：以 \`detailed-design.md\` 为基础，填写 Why、What Changes、Capabilities、Impact。
  - Capabilities 章节非常关键，其中列出的每个 capability 都需要对应一个 spec file。
- **specs/<capability>/spec.md**：为 proposal 的 Capabilities 章节中列出的每个 capability 创建一个 spec（使用 capability 名，而不是 change 名）。
- **design.md**：创建一个面向实现的技术设计文档，综合 \`proposal.md\`、\`specs\` 以及（如果存在）\`detailed-design.md\`。
  - 如果 \`detailed-design.md\` 存在，在生成 \`design.md\` 前 MUST 先读取它。
  - 保留会影响实现的关键细节，例如接口约束、关键流程、持久化/数据库变更、外部依赖、安全限制和 rollout 要求。
  - 不要机械复制 \`detailed-design.md\` 的公司格式标题；应将内容重组到 \`design.md\` 模板结构中。
- **tasks.md**：将实现工作拆分为带 checkbox 的任务列表。

对于其他 schemas，遵循 CLI 输出中的 \`instruction\` 字段。

**Guardrails**
- 每次调用只创建 ONE artifact
- 在 review 中，\`requirements.md\` 和 \`detailed-design.md\` 必须作为 \`proposal.md\` 之前的前置项
- 创建新 artifact 前始终先读取 dependency artifacts
- 不要跳过 artifact，也不要乱序创建
- 如果上下文不清楚，先向用户确认，再创建
- 写入后先确认 artifact 文件确实存在，再汇报进度
- 遵循 schema 定义的 artifact 顺序，不要自行假设固定 artifact 名称
- **IMPORTANT**：\`context\` 和 \`rules\` 是给你的约束，不是文件内容
  - 不要把 \`<context>\`、\`<rules>\`、\`<project_context>\` 这些块复制进 artifact
  - 它们只用于指导你写什么，不应直接出现在输出中`
  };
}
