/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getReviewChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'infra-review-change',
    description: 'Review an artifact before creating the next artifact. Use when the user wants to review their change progress, create the next artifact, or continue the workflow under the review command.',
    instructions: `Continue working on a change by creating the next artifact.

**Input**: Optionally specify a change name. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`infraspec list --json\` to get available changes sorted by most recently modified. Then use the **AskUserQuestion tool** to let the user select which change to work on.

   Present the top 3-4 most recently modified changes as options, showing:
   - Change name
   - Schema (from \`schema\` field if present, otherwise "spec-driven")
   - Status (e.g., "0/5 tasks", "complete", "no tasks")
   - How recently it was modified (from \`lastModified\` field)

   Mark the most recently modified change as "(Recommended)" since it's likely what the user wants to continue.

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check current status**
   Before using the artifact workflow, check whether the two pre-spec documents for this review flow already exist:
   - \`infraspec/changes/<name>/requirements.md\`
   - \`infraspec/changes/<name>/detailed-design.md\`

   The fixed review flow is:
   \`requirements -> detailed-design -> proposal -> specs/design -> tasks\`

   Handle the pre-spec documents first:

   - If \`requirements.md\` does not exist:
     - Create it from the user's requirement document or the best available conversation context.
     - If the requirements are ambiguous or incomplete, ask the user before writing it.
     - Save it to \`infraspec/changes/<name>/requirements.md\`.
     - STOP after creating only this file.

   - If \`requirements.md\` exists but \`detailed-design.md\` does not:
     - Read \`requirements.md\`.
     - Create \`detailed-design.md\` using the company's required design-document format.
     - Generate it in Markdown using this exact section order:
       - \`# 详细设计文档\`
       - \`## 1. 引言\`
       - \`### 1.1 目的\`
       - \`### 1.2 统一术语\`
       - \`## 2. 应用架构详细设计\`
       - \`### 2.1 接口设计\`
       - \`#### 2.1.1 <接口名称> 接口\`
       - \`### 2.2 业务功能的流程设计\`
       - \`#### 2.2.1 <功能名称> 功能流程设计\`
       - \`### 2.3 领域模型设计（可选）\`
       - \`#### 2.3.1 <实体名称> 实体设计\`
       - \`### 2.4 持久化模型设计（可选）\`
       - \`#### 2.4.1 <持久化模型名称> 持久化模型设计\`
       - \`### 2.5 技术参数变更的流程设计（可选）\`
       - \`#### 2.5.1 <参数或流程名称> 流程设计\`
       - \`## 3. 系统架构详细设计\`
       - \`### 3.1 数据库详细设计\`
       - \`#### 3.1.1 数据库表设计\`
       - \`#### 3.1.2 数据库索引设计\`
       - \`### 3.2 云服务落地方案\`
       - \`#### 3.2.1 <云服务名称> 云服务\`
     - Section requirements:
       - Interface design MUST cover purpose, caller/callee, method/path, request params, response, error handling, and security/auth.
       - Business flow design MUST cover goal, preconditions, main flow, exception flow, inputs/outputs, and flow notes.
       - Optional sections MUST either contain concrete content or explicitly state \`本次不涉及\`.
       - Database design MUST explicitly state \`本次不涉及\` if there are no schema/index changes.
       - Cloud service design MUST explicitly state \`本次不涉及\` if no cloud resource changes are required.
     - Generation rules:
       - Base the document on \`requirements.md\` first, then use reasonable engineering inference where necessary.
       - Replace every placeholder with concrete names.
       - Do not output an empty outline.
       - If requirements are insufficient, mark the missing parts as \`待确认事项\` instead of inventing facts.
     - Save it to \`infraspec/changes/<name>/detailed-design.md\`.
     - STOP after creating only this file.

   - Only after both files exist, continue with the existing artifact workflow below.

   Then check the current InfraSpec artifact status:
   \`\`\`bash
   infraspec status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand current state. The response includes:
   - \`schemaName\`: The workflow schema being used (e.g., "spec-driven")
   - \`artifacts\`: Array of artifacts with their status ("done", "ready", "blocked")
   - \`isComplete\`: Boolean indicating if all artifacts are complete

3. **Act based on status**:

   ---

   **If all artifacts are complete (\`isComplete: true\`)**:
   - Congratulate the user
   - Show final status including the schema used
   - Suggest: "All artifacts created! You can now implement this change or archive it."
   - STOP

   ---

   **If artifacts are ready to create** (status shows artifacts with \`status: "ready"\`):
   - Pick the FIRST artifact with \`status: "ready"\` from the status output
   - Get its instructions:
     \`\`\`bash
     infraspec instructions <artifact-id> --change "<name>" --json
     \`\`\`
   - Parse the JSON. The key fields are:
     - \`context\`: Project background (constraints for you - do NOT include in output)
     - \`rules\`: Artifact-specific rules (constraints for you - do NOT include in output)
     - \`template\`: The structure to use for your output file
     - \`instruction\`: Schema-specific guidance
     - \`outputPath\`: Where to write the artifact
     - \`dependencies\`: Completed artifacts to read for context
   - **Create the artifact file**:
     - Read any completed dependency files for context
     - Use \`template\` as the structure - fill in its sections
     - Apply \`context\` and \`rules\` as constraints when writing - but do NOT copy them into the file
     - Write to the output path specified in instructions
   - Show what was created and what's now unlocked
   - STOP after creating ONE artifact

   ---

   **If no artifacts are ready (all blocked)**:
   - This shouldn't happen with a valid schema
   - Show status and suggest checking for issues

4. **After creating an artifact, show progress**
   \`\`\`bash
   infraspec status --change "<name>"
   \`\`\`

**Output**

After each invocation, show:
- Which artifact was created
- Schema workflow being used
- Current progress (N/M complete)
- What artifacts are now unlocked
- Prompt: name the artifact just created and the next ready artifact(s)
  - Example: "You can now review \`<created-artifact>\` and then run \`/infra:review\` again to create the next artifact (\`design\` or \`specs\`)."

For the two pre-spec documents:
- \`requirements.md\`: distilled requirements from the user's requirement document
- \`detailed-design.md\`: company-format detailed design derived from \`requirements.md\`
- These two files are mandatory in review before proposal/specs/design/tasks
- They are part of the review flow even though the later InfraSpec status output still tracks only the existing schema artifacts

**Artifact Creation Guidelines**

The artifact types and their purpose depend on the schema. Use the \`instruction\` field from the instructions output to understand what to create.

Common artifact patterns:

**review pre-spec documents**:
- **requirements.md**: Capture the user's requirement document in a concise, implementation-ready form. Preserve scope, constraints, actors, inputs/outputs, and acceptance expectations.
- **detailed-design.md**: Produce the company-required detailed design document from \`requirements.md\`. Follow the required company structure exactly.
  - Required structure:
    - \`1. 引言\` → \`1.1 目的\`, \`1.2 统一术语\`
    - \`2. 应用架构详细设计\` → \`2.1 接口设计\`, \`2.2 业务功能的流程设计\`, \`2.3 领域模型设计（可选）\`, \`2.4 持久化模型设计（可选）\`, \`2.5 技术参数变更的流程设计（可选）\`
    - \`3. 系统架构详细设计\` → \`3.1 数据库详细设计\`, \`3.2 云服务落地方案\`
  - Optional sections must explicitly say \`本次不涉及\` when not applicable.
  - Unknown details must be marked as \`待确认事项\`.

**spec-driven schema** (proposal → specs → design → tasks):
- **proposal.md**: Base this on \`detailed-design.md\`. Fill in Why, What Changes, Capabilities, Impact.
  - The Capabilities section is critical - each capability listed will need a spec file.
- **specs/<capability>/spec.md**: Create one spec per capability listed in the proposal's Capabilities section (use the capability name, not the change name).
- **design.md**: Document technical decisions, architecture, and implementation approach.
- **tasks.md**: Break down implementation into checkboxed tasks.

For other schemas, follow the \`instruction\` field from the CLI output.

**Guardrails**
- Create ONE artifact per invocation
- In review, treat \`requirements.md\` and \`detailed-design.md\` as required predecessors before creating \`proposal.md\`
- Always read dependency artifacts before creating a new one
- Never skip artifacts or create out of order
- If context is unclear, ask the user before creating
- Verify the artifact file exists after writing before marking progress
- Use the schema's artifact sequence, don't assume specific artifact names
- **IMPORTANT**: \`context\` and \`rules\` are constraints for YOU, not content for the file
  - Do NOT copy \`<context>\`, \`<rules>\`, \`<project_context>\` blocks into the artifact
  - These guide what you write, but should never appear in the output`,
    license: 'MIT',
    compatibility: 'Requires InfraSpec CLI (`infraspec`).',
    metadata: { author: 'bianyongmei', version: '1.0' },
  };
}

export function getOpsxReviewCommandTemplate(): CommandTemplate {
  return {
    name: 'INFRA: Review',
    description: 'Review a change - create the next artifact (Experimental)',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `Continue working on a change by creating the next artifact.

**Input**: Optionally specify a change name after \`/infra:review\` (e.g., \`/infra:review add-auth\`). If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`infraspec list --json\` to get available changes sorted by most recently modified. Then use the **AskUserQuestion tool** to let the user select which change to work on.

   Present the top 3-4 most recently modified changes as options, showing:
   - Change name
   - Schema (from \`schema\` field if present, otherwise "spec-driven")
   - Status (e.g., "0/5 tasks", "complete", "no tasks")
   - How recently it was modified (from \`lastModified\` field)

   Mark the most recently modified change as "(Recommended)" since it's likely what the user wants to continue.

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check current status**
   Before using the artifact workflow, check whether the two pre-spec documents for this review flow already exist:
   - \`infraspec/changes/<name>/requirements.md\`
   - \`infraspec/changes/<name>/detailed-design.md\`

   The fixed review flow is:
   \`requirements -> detailed-design -> proposal -> specs/design -> tasks\`

   Handle the pre-spec documents first:

   - If \`requirements.md\` does not exist:
     - Create it from the user's requirement document or the best available conversation context.
     - If the requirements are ambiguous or incomplete, ask the user before writing it.
     - Save it to \`infraspec/changes/<name>/requirements.md\`.
     - STOP after creating only this file.

   - If \`requirements.md\` exists but \`detailed-design.md\` does not:
     - Read \`requirements.md\`.
     - Create \`detailed-design.md\` using the company's required design-document format.
     - Generate it in Markdown using this exact section order:
       - \`# 详细设计文档\`
       - \`## 1. 引言\`
       - \`### 1.1 目的\`
       - \`### 1.2 统一术语\`
       - \`## 2. 应用架构详细设计\`
       - \`### 2.1 接口设计\`
       - \`#### 2.1.1 <接口名称> 接口\`
       - \`### 2.2 业务功能的流程设计\`
       - \`#### 2.2.1 <功能名称> 功能流程设计\`
       - \`### 2.3 领域模型设计（可选）\`
       - \`#### 2.3.1 <实体名称> 实体设计\`
       - \`### 2.4 持久化模型设计（可选）\`
       - \`#### 2.4.1 <持久化模型名称> 持久化模型设计\`
       - \`### 2.5 技术参数变更的流程设计（可选）\`
       - \`#### 2.5.1 <参数或流程名称> 流程设计\`
       - \`## 3. 系统架构详细设计\`
       - \`### 3.1 数据库详细设计\`
       - \`#### 3.1.1 数据库表设计\`
       - \`#### 3.1.2 数据库索引设计\`
       - \`### 3.2 云服务落地方案\`
       - \`#### 3.2.1 <云服务名称> 云服务\`
     - Section requirements:
       - Interface design MUST cover purpose, caller/callee, method/path, request params, response, error handling, and security/auth.
       - Business flow design MUST cover goal, preconditions, main flow, exception flow, inputs/outputs, and flow notes.
       - Optional sections MUST either contain concrete content or explicitly state \`本次不涉及\`.
       - Database design MUST explicitly state \`本次不涉及\` if there are no schema/index changes.
       - Cloud service design MUST explicitly state \`本次不涉及\` if no cloud resource changes are required.
     - Generation rules:
       - Base the document on \`requirements.md\` first, then use reasonable engineering inference where necessary.
       - Replace every placeholder with concrete names.
       - Do not output an empty outline.
       - If requirements are insufficient, mark the missing parts as \`待确认事项\` instead of inventing facts.
     - Save it to \`infraspec/changes/<name>/detailed-design.md\`.
     - STOP after creating only this file.

   - Only after both files exist, continue with the existing artifact workflow below.

   Then check the current InfraSpec artifact status:
   \`\`\`bash
   infraspec status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand current state. The response includes:
   - \`schemaName\`: The workflow schema being used (e.g., "spec-driven")
   - \`artifacts\`: Array of artifacts with their status ("done", "ready", "blocked")
   - \`isComplete\`: Boolean indicating if all artifacts are complete

3. **Act based on status**:

   ---

   **If all artifacts are complete (\`isComplete: true\`)**:
   - Congratulate the user
   - Show final status including the schema used
   - Suggest: "All artifacts created! You can now implement this change with \`/infra:apply\` or archive it with \`/infra:archive\`."
   - STOP

   ---

   **If artifacts are ready to create** (status shows artifacts with \`status: "ready"\`):
   - Pick the FIRST artifact with \`status: "ready"\` from the status output
   - Get its instructions:
     \`\`\`bash
     infraspec instructions <artifact-id> --change "<name>" --json
     \`\`\`
   - Parse the JSON. The key fields are:
     - \`context\`: Project background (constraints for you - do NOT include in output)
     - \`rules\`: Artifact-specific rules (constraints for you - do NOT include in output)
     - \`template\`: The structure to use for your output file
     - \`instruction\`: Schema-specific guidance
     - \`outputPath\`: Where to write the artifact
     - \`dependencies\`: Completed artifacts to read for context
   - **Create the artifact file**:
     - Read any completed dependency files for context
     - Use \`template\` as the structure - fill in its sections
     - Apply \`context\` and \`rules\` as constraints when writing - but do NOT copy them into the file
     - Write to the output path specified in instructions
   - Show what was created and what's now unlocked
   - STOP after creating ONE artifact

   ---

   **If no artifacts are ready (all blocked)**:
   - This shouldn't happen with a valid schema
   - Show status and suggest checking for issues

4. **After creating an artifact, show progress**
   \`\`\`bash
   infraspec status --change "<name>"
   \`\`\`

**Output**

After each invocation, show:
- Which artifact was created
- Schema workflow being used
- Current progress (N/M complete)
- What artifacts are now unlocked
- Prompt: name the artifact just created and the next ready artifact(s)
  - Example: "You can now review \`<created-artifact>\` and then run \`/infra:review\` again to create the next artifact (\`design\` or \`specs\`)."

For the two pre-spec documents:
- \`requirements.md\`: distilled requirements from the user's requirement document
- \`detailed-design.md\`: company-format detailed design derived from \`requirements.md\`
- These two files are mandatory in review before proposal/specs/design/tasks
- They are part of the review flow even though the later InfraSpec status output still tracks only the existing schema artifacts

**Artifact Creation Guidelines**

The artifact types and their purpose depend on the schema. Use the \`instruction\` field from the instructions output to understand what to create.

Common artifact patterns:

**review pre-spec documents**:
- **requirements.md**: Capture the user's requirement document in a concise, implementation-ready form. Preserve scope, constraints, actors, inputs/outputs, and acceptance expectations.
- **detailed-design.md**: Produce the company-required detailed design document from \`requirements.md\`. Follow the required company structure exactly.
  - Required structure:
    - \`1. 引言\` → \`1.1 目的\`, \`1.2 统一术语\`
    - \`2. 应用架构详细设计\` → \`2.1 接口设计\`, \`2.2 业务功能的流程设计\`, \`2.3 领域模型设计（可选）\`, \`2.4 持久化模型设计（可选）\`, \`2.5 技术参数变更的流程设计（可选）\`
    - \`3. 系统架构详细设计\` → \`3.1 数据库详细设计\`, \`3.2 云服务落地方案\`
  - Optional sections must explicitly say \`本次不涉及\` when not applicable.
  - Unknown details must be marked as \`待确认事项\`.

**spec-driven schema** (proposal → specs → design → tasks):
- **proposal.md**: Base this on \`detailed-design.md\`. Fill in Why, What Changes, Capabilities, Impact.
  - The Capabilities section is critical - each capability listed will need a spec file.
- **specs/<capability>/spec.md**: Create one spec per capability listed in the proposal's Capabilities section (use the capability name, not the change name).
- **design.md**: Document technical decisions, architecture, and implementation approach.
- **tasks.md**: Break down implementation into checkboxed tasks.

For other schemas, follow the \`instruction\` field from the CLI output.

**Guardrails**
- Create ONE artifact per invocation
- In review, treat \`requirements.md\` and \`detailed-design.md\` as required predecessors before creating \`proposal.md\`
- Always read dependency artifacts before creating a new one
- Never skip artifacts or create out of order
- If context is unclear, ask the user before creating
- Verify the artifact file exists after writing before marking progress
- Use the schema's artifact sequence, don't assume specific artifact names
- **IMPORTANT**: \`context\` and \`rules\` are constraints for YOU, not content for the file
  - Do NOT copy \`<context>\`, \`<rules>\`, \`<project_context>\` blocks into the artifact
  - These guide what you write, but should never appear in the output`
  };
}
